name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0
      - name: Building...
        run: processing-java --sketch=$PWD --output=$HOME/out/build --build
      - run: mv $GITHUB_WORKSPACE/CHANGELOG.md $HOME/out/export/CHANGELOG.md
      - name: Exporting CHANGELOG.md
        uses: actions/upload-artifact@v2
        with:
          name: windows_export
          path: ~/out/export/CHANGELOG.md

  build-windows:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0    
        with:
          version: '3.5.4'
      - name: Exporting...
        run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=windows --export
      - run: ls -lah $HOME/out/export
      - name: Creating an artifact of the export...
        uses: actions/upload-artifact@v2
        with:
          name: windows_export
          path: ~/out/export/
  
  # build-macosx:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ifP1/setup-processing@v0.3.0    
  #     with:
  #       version: '3.5.4'
  #   - name: Exporting...
  #     run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=macosx --export
  #   - run: ls -lah $HOME/out/export
  #   - name: Creating an artifact of the export...
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: macosx_export
  #       path: ~/out/export/
        
  build-linux:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0
        with:
          version: '3.5.4'
      - name: Exporting...
        run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=linux --export
      - run: ls -lah $HOME/out/export
      - name: Creating an artifact of the export...
        uses: actions/upload-artifact@v2
        with:
          name: linux_export
          path: ~/out/export/

  release:
    needs:
      - build-linux
      - build-windows
    runs_on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          path: ~/out/export/
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Path to load note-worthy description of changes in release from
          body_path: ${{home}}/out/export/CHANGELOG.md
          # Newline-delimited list of path globs for asset files to upload
          files: |
            '$HOME/out/export/linux_export'
            '$HOME/out/export/windows_export'
        env:
          - GITHUB_TOKEN: ${{secrets.github}}