name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      PREFIX: ${{steps.get_file.outputs.PREFIX}}
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v1.0.2
        with:
          version: 3.5.4
      - name: Get file prefix
        id: get_file
        run: echo ::set-output name=PREFIX::${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}-${GITHUB_REF/refs\/tags\//}
      - name: Building...
        run: processing-java --sketch=$PWD --build
        
  build:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v1.0.2
        with:
          version: 3.5.4
      - name: Exporting windows application...
        run: processing-java --sketch=$PWD --output=out/${{needs.test.outputs.PREFIX}}-windows --no-java --platform=windows --export
      - name: Exporting linux application...
        run: processing-java --sketch=$PWD --output=out/${{needs.test.outputs.PREFIX}}-linux --no-java --platform=linux --export
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: out/*

  release:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
      - name: Compressing and Packaging...
        run: |
          cd artifact
          tar -czvf ../${{needs.test.outputs.PREFIX}}-linux.tar.gz ${{needs.test.outputs.PREFIX}}-linux/
          zip -r ../${{needs.test.outputs.PREFIX}}-windows.zip ${{needs.test.outputs.PREFIX}}-windows/
      - name: GitHub Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: |
            *-linux.tar.gz
            *-windows.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: "ftp://gymnasium-melle.org:21"
          user: "quang.thanh.ta"
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "artifact"
          remoteDir: "/group/abi21.ifp1/Files/Java/Target/Reaktionszeit"