name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0
      - name: Building...
        run: processing-java --sketch=$PWD --output=$HOME/out/build --build

  build-windows:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0    
        with:
          version: '3.5.4'
      - name: Exporting...
        run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=windows --export
      - run: ls -lah $HOME/out/export
      - name: Creating an artifact of the export...
        uses: actions/upload-artifact@v2
        with:
          name: windows_export
          path: ~/out/export/
        
  build-linux:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v0.3.0
        with:
          version: '3.5.4'
      - name: Exporting...
        run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=linux --export
      - run: ls -lah $HOME/out/export
      - name: Creating an artifact of the export...
        uses: actions/upload-artifact@v2
        with:
          name: linux_export
          path: ~/out/export/

  release:
    needs:
      - build-linux
      - build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ls -lah
      - run: ls -lah  
      - run: ls -lah linux_export
      - run: ls -lah windows_export
      - name: Compressing...
        run: |
          tar -czvf linux_export.tar.gz linux_export/
          zip -r windows_export windows_export/
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Path to load note-worthy description of changes in release from
          body_path: ${{github.workspace}}/CHANGELOG.md
          # Newline-delimited list of path globs for asset files to upload
          files: |
            linux_export.tar.gz
            windows_export.zip
        env:
          GITHUB_TOKEN: ${{secrets.github}}
