name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v1.0.2
        with:
          version: 3.5.4
      - name: Building...
        run: processing-java --sketch=$PWD --build
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}  
        
  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      REPO_NAME_PATH: Reaktionszeit
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v1.0.2
        with:
          version: 3.5.4
      - name: Exporting windows application...
        run: processing-java --sketch=$PWD --output=${REPO_NAME_PATH}-windows --no-java --platform=windows --export
      - name: Exporting linux application...
        run: processing-java --sketch=$PWD --output=${REPO_NAME_PATH}-linux --no-java --platform=linux --export
      - name: Compressing...
        run: |
          tar -czvf application-linux.tar.gz ${REPO_NAME_PATH}-linux/
          zip -r application-windows.zip ${REPO_NAME_PATH}-windows/
      - name: GitHub Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: ${{github.workspace}}/CHANGELOG.md
          files: |
            application-linux.tar.gz
            application-windows.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
