name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ifP1/setup-processing@v0.3.0
    - name: Building...
      run: processing-java --sketch=$PWD --output=$HOME/out/build --build

  build-windows:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ifP1/setup-processing@v0.3.0    
      with:
        version: '3.5.4'
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=windows --export
    - run: ls -lah $HOME/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: windows_export
        path: ~/out/export/
  
  build-macosx:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ifP1/setup-processing@v0.3.0    
      with:
        version: '3.5.4'
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=macosx --export
    - run: ls -lah $HOME/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: macosx_export
        path: ~/out/export/
        
  build-linux:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ifP1/setup-processing@v0.3.0
      with:
        version: '3.5.4'
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$HOME/out/export --no-java --platform=linux --export
    - run: ls -lah $HOME/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: linux_export
        path: ~/out/export/
