name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.1.2
    - run: pwd
    - name: Building...
      run: processing-java --build --sketch=. --output=out/build
    - name: Exporting...
      run: processing-java --build --sketch=. --output=out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        path: out/export
