name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.3.0
    - name: Building...
      run: processing-java --sketch=$PWD --output=$HOME/out/build --build
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$HOME/out/export --export
    - run: pwd
    - run: ls -lah
    - run: ls -lah ~
    - run: ls -lah $HOME/out/build
    - run: ls -lah $HOME/out/export
    - run: ls -lah $HOME/out/export/Reaktionszeit
    - run: ls -lah $HOME/out/export/lib
    - run: ls -lah $HOME/out/export/source
    - run: ls -lah $HOME/out/export/java
    - run: cd ~
    - run: pwd
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        path: ~/out/export/
