name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.3.0
    - name: Building...
      run: processing-java --sketch=$PWD --output=$GITHUB_WORKSPACE/out/build --build

  build-windows:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.3.0    
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$GITHUB_WORKSPACE/out/export --no-java --export --platform 'windows'
    - run: ls -lah $GITHUB_WORKSPACE/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: windows_export
        path: $GITHUB_WORKSPACE/out/export/
  
  build-macosx:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.3.0    
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$GITHUB_WORKSPACE/out/export --no-java --export --platform 'macosx'
    - run: ls -lah $GITHUB_WORKSPACE/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: macosx_export
        path: $GITHUB_WORKSPACE/out/export/
        
  build-linux:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - uses: ifP1/setup-processing@v0.3.0    
    - name: Exporting...
      run: processing-java --sketch=$PWD --output=$GITHUB_WORKSPACE/out/export --no-java --export --platform 'linux'
    - run: ls -lah $GITHUB_WORKSPACE/out/export
    - name: Creating an artifact of the export...
      uses: actions/upload-artifact@v2
      with:
        name: linux_export
        path: $GITHUB_WORKSPACE/out/export/
