name: Test

on: 
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      PREFIX: ${{steps.get_file.outputs.PREFIX}}
    steps:
      - uses: actions/checkout@v2
      - uses: ifP1/setup-processing@v1.0.2
        with:
          version: 3.5.4
      - name: Building...
        run: processing-java --sketch=$PWD --build
        